### ISSUE TITLE
Invalid Scenario file crashes the program

### ISSUE THREAD

**Issue by Nasiff** [connorAhearn/Braille_Project#1]
**Description**
Opening a non-valid scenario file results in the entire program crashing.

**Expected Vs Actual**
Expected result: The program handles the error and shows that it is not a valid scenario file and then returns back to the file selection screen or the main menu.

Actual result: The program not only crashes but the voice of the Visual player still lingers with the words that an error has occurred.

**Steps to reproduce:**

1.  Upon opening of the app, choose the 'Test Scenario' option.
2.  Choose Visual Player.
3.  Select a file that is anything but a scenario file.

**Operating System** 
Windows 10 Pro, 64 Bit, x64 based processor; _Version:_ 1709; _OS Build:_ 16299.248
**Java Version**
Version 8, Update 144 (build 1.8.0_144-b01)

**Comment by connorAhearn** [comment]
Fixed!
